---
title: "LFMM_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{LFMM_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(algatr)
library("here")
#to install LFMM:
#devtools::install_github("bcm-uga/lfmm")
library("lfmm") 
library("tidyverse")

#libraries for k selection
library("AssocTests")
library("tess3r")

devtools::load_all()
```

### Load Test Data

```{r, warning = FALSE}
load_example()
```

# Run LFMM

## Comparing different LFMM methods

```{r, warning = FALSE,  results = FALSE, message = FALSE, warning = FALSE}
results <- lfmm_run(gen, env, lfmm_method = "ridge")
```
```{r}
results
```


```{r, results = FALSE, message = FALSE, warning = FALSE}
results <- lfmm_run(gen, env, lfmm_method = "lasso")
```

## Comparing different K selection methods

```{r, warning = FALSE,  results=FALSE, warning = FALSE}
results_tw <- lfmm_run(gen, env, k_selection = "tracy.widom")
```


```{r, results = FALSE, warning = FALSE}
results_qe <- lfmm_run(gen, env, k_selection = "quick.elbow")
```

```{r, results = FALSE, cache = TRUE, warning = FALSE}
results_tess <- lfmm_run(gen, env, coords, k_selection = "tess", Kvals = 1:20)
```

```{r}
results_tw
results_qe
results_tess
```

