---
title: "LFMM"
output: html_document
---

# Setup
```{r, warning = FALSE, message = FALSE}
library("ccgplandgen")
library("here")
#to install LFMM:
#devtools::install_github("bcm-uga/lfmm")
library("lfmm") 
library("tidyverse")

#libraries for k seleciton
library("AssocTests")
library("tess3r")

devtools::load_all()
```

### Load Test Data

```{r, warning = FALSE}
# gen matrix
# TODO: make sure to make it clear it's LFMM 2.0 (citation) not 1
gen <- read.csv(here("test_data","gen_dosage_mat.csv"))
gen <- gen[,-1]

# coords
coords <- read.table(here("test_data","Scelop.coord"))
coords <- as.matrix(coords)

# And a set of worldclim rasters for the study area
# And a set of worldclim rasters for the study area
env_files <- list.files(here("data","PC_layers"), full.names = TRUE)
envstack <- raster::stack(env_files)

#make env
env <- raster::extract(envstack, coords)
env <- data.frame(env)
```

# Run LFMM

## Comparing different LFMM methods

```{r, warning = FALSE,  results = FALSE, message = FALSE, warning = FALSE}
results <- lfmm_run(gen, env, lfmm_method = "ridge")
```
```{r}
results
```


```{r, results = FALSE, message = FALSE, warning = FALSE}
results <- lfmm_run(gen, env, lfmm_method = "lasso")
```

## Comparing different K selection methods

```{r, warning = FALSE,  results=FALSE, warning = FALSE}
results_tw <- lfmm_run(gen, env, k_selection = "tracy.widom")
```


```{r, results = FALSE, warning = FALSE}
results_qe <- lfmm_run(gen, env, k_selection = "quick.elbow")
```

```{r, results = FALSE, cache = TRUE, warning = FALSE}
results_tess <- lfmm_run(gen, env, coords, k_selection = "tess", Kvals = 1:20)
```

```{r}
results_tw
results_qe
results_tess
```

