---
title: "RDA_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RDA_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<<<<<<< HEAD:vignettes/RDA_vignette.Rmd
```{r setup, warning=FALSE, message=FALSE}
library(algatr)
library("here")
library("gt")
# RDA
library("vegan")
library("raster")
library("robust")
library("tidyverse")
# BiocManager::install("qvalue")
library("qvalue")
devtools::load_all()
```

### Load Test Data

```{r, warning = FALSE}
load_example()
gen <- vcf_to_dosage(liz_vcf)
coords <- liz_coords
env <- CA_env
```

# Run RDA
```{r, warning = FALSE, message = FALSE}
results <- rda_do_everything(gen, env, coords, 
                            correctGEO = FALSE, 
                            correctPC = FALSE,
                            outlier_method = "p",
                            sig = 0.05, 
                            padj_method = "fdr")
```

```{r}
results <- rda_do_everything(gen, env, coords, 
                            correctGEO = FALSE, 
                            correctPC = FALSE,
                            outlier_method = "z",
                            z = 3, 
                            padj_method = "fdr")
```



# Partial RDAs

## Geo correction
```{r, warning = TRUE, message = FALSE}
results <- rda_do_everything(gen, 
                            env, 
                            coords, 
                            model = "full",
                            correctGEO = TRUE, 
                            correctPC = FALSE,
                            sig = 0.05, 
                            padj_method = "fdr")
```

## PC correction
```{r, warning = TRUE, message = FALSE}
results <- rda_do_everything(gen, 
                            env, 
                            coords, 
                            model = "full",
                            correctGEO = FALSE, 
                            correctPC = TRUE,
                            sig = 0.05, 
                            padj_method = "fdr")
```

## PC + Geo Correction
```{r, warning = TRUE, message = FALSE}
results <- rda_do_everything(gen, 
                            env, 
                            coords, 
                            model = "full",
                            correctGEO = TRUE, 
                            correctPC = TRUE,
                            sig = 0.05, 
                            padj_method = "fdr")
```

## Variable selection

```{r, warning = TRUE, message = FALSE}
results <- rda_do_everything(gen, 
                            env, 
                            coords, 
                            model = "best",
                            correctGEO = FALSE, 
                            correctPC = FALSE,
                            sig = 0.05, 
                            padj_method = "fdr")
```

## Separate functions

### 1. Prepare data
```{r}
# Extract and standardize environmental variables
env <- raster::extract(CA_env, coords)
env <- scale(env, center = TRUE, scale = TRUE) 
env <- data.frame(env)
    
# Remove any NA values
if(any(is.na(env))){
  warning("NA values found in env data, removing rows with NAs for RDA")
  gen <- gen[complete.cases(env),]
  coords <- coords[complete.cases(env),]
  env <- env[complete.cases(env),]
}
if(any(is.na(gen))){
  warning("NA values found in gen data, removing rows with NAs for RDA")
  env <- env[complete.cases(gen),]
  coords <- coords[complete.cases(gen),]
  gen <- gen[complete.cases(gen),]
}
```

### 2. Run RDA
```{r}
mod <- rda_run(gen, env, correctGEO = FALSE, correctPC = FALSE)
```


### 3. Identify candidate snps
```{r}

# Running with all axes and z method
rda_sig <- rda_getoutliers(mod, naxes = "all", outlier_method = "z", z = 3)
rda_snps <- rda_sig[["rda_snps"]]
length(rda_snps)

# Running with all axes and p method
rda_sig <- rda_getoutliers(mod, naxes = "all", outlier_method = "p", padj_method = "fdr", sig = 0.01)
rda_snps <- rda_sig[["rda_snps"]]
pvalues <- rda_sig[["pvalues"]]
length(rda_snps)

```

### 4. Identify environmental associations
```{r}
rda_gen <- gen[,rda_snps]
cor_df <- rda_cor(rda_gen, env)

# You can make a pretty table from these results (here we are displaying only the first 5 rows):
rda_table(cor_df, nrow = 5)

# you can order by the strength of the correlation
rda_table(cor_df, order = TRUE, nrow = 5)

# you can choose to only keep the top variable for each SNP the table by the strength of the correlation
rda_table(cor_df, top = TRUE, nrow = 5)

# you can display only select environmental variables
rda_table(cor_df, var = "CA_rPCA1", nrow = 5)

# putting it all together we can display the top 5, ordered SNPS for each variable
rda_table(cor_df, top = TRUE, order = TRUE, var = "CA_rPCA1", nrow = 5)
rda_table(cor_df, top = TRUE, order = TRUE, var = "CA_rPCA2", nrow = 5)
rda_table(cor_df, top = TRUE, order = TRUE, var = "CA_rPCA3", nrow = 5)
```

### 5. Plot results

```{r, fig.width = 6, fig.height = 5}
rda_plot(mod, rda_snps, biplot_axes = c(1,3), rdaplot = TRUE)
rda_plot(mod, rda_snps, biplot_axes = c(2,3), rdaplot = TRUE)
rda_plot(mod, rda_snps, pvalues, sig = 0.05, manhattan = TRUE, rdaplot = FALSE)

# note: if only one axis is provided, a histogram will be generated
rda_plot(mod, rda_snps, axes = 1, rdaplot = TRUE, binwidth = 0.01)
```

