---
title: "TESS"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Setup

```{r, warning = FALSE, message = FALSE}
library("here")
library("tidyverse")
library("raster")
library("rgdal")
# Figure out libraries later
# to install TESS:
# install.packages("devtools")
# devtools::install_github("bcm-uga/TESS3_encho_sen")
library("tess3r") 


#for plotting (from TESS)
source("http://membres-timc.imag.fr/Olivier.Francois/Conversion.R")
source("http://membres-timc.imag.fr/Olivier.Francois/POPSutilities.R")

# need LEA library for cross entropy

#if (!requireNamespace("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
#BiocManager::install("LEA")
library("LEA")

# devtools::install_github("cran/automap")
library("automap")
library("spatialEco")

devtools::load_all()
```
### Load Test Data

```{r, warning = FALSE}
# gen matrix
gen <- read.csv(here("test_data","gen_dosage_mat.csv"))
gen <- gen[,-1]

# coords
coords <- read.table(here("test_data","Scelop.coord"))
coords <- as.matrix(coords)

```

```{r}
# CA shape file
CA_boundary <- readOGR(here("data","CA_State","CA_State_TIGER2016.shp"))
spdf <- CA_boundary
```


# Do everything function
```{r, cache = TRUE, results = FALSE, warning = FALSE}
tess_full(gen, coords, Kvals = 1:3, spdf = CA_boundary, ploidy = 2, n_cell = 10000, k_selection = "auto", plot_method = "max", minQ = 0.20)
```


# Plotting 

## Example TESS

### Run TESS
```{r}
K = 10
```


```{r, cache = TRUE}
tess3_obj <- tess3(X = gen, coord = coords, K = 1:K, ploidy = 2) 
```

### Krig Q values

```{r, cache = TRUE, results = FALSE, warning = FALSE}
krig_list <- list()
for(i in 2:K){
  qmat <- qmatrix(tess3_obj, K = i)
  krig_admix <- tess_krig(qmat, coords, spdf, n_cell = 10000)
  krig_list[[i]] <- krig_admix
}
```
## Basic plotting 

```{r, fig.width = 12, fig.height=15, warning = FALSE}
par(pty = "s", mfrow = c(K, 6), mar = rep(0,4))
for(i in 2:K){
  krig_admix <- krig_list[[i]]
  tess_rainbow_plot(krig_admix, coords, spdf, plot_method = "max", alpha = 1)
  tess_rainbow_plot(krig_admix, coords, spdf, plot_method = "all", alpha = 0.9, minQ = 0.1)
  tess_rainbow_plot(krig_admix, coords, spdf, plot_method = "max", alpha = 0.9, reclassify = TRUE)
  tess_rainbow_plot(krig_admix, coords, spdf, plot_method = "all", alpha = 0.9, reclassify = TRUE)
  tess_rainbow_plot(krig_admix, coords, spdf, plot_method = "max_poly", alpha = 0.9)
  tess_rainbow_plot(krig_admix, coords, spdf, plot_method = "all_poly", alpha = 0.5, minQ = 1/i)
}
```

## Plotting Max Q

**TODO: turn this code into functions**

```{r, cache = TRUE, warning = FALSE, output = FALSE, fig.width = 90}
rs <- stack_maxQ(krig_list)
```

```{r, fig.width = 8, fig.height = 4}
rmean <- calc(rs, mean)

rvar <- rmean
m <- matrix(rep(1,9), nrow = 3)
rvar <- focal(rvar, w = m, fun = var)

par(mfrow = c(1,2), mar = rep(1,4), oma = rep(2,4))
plot(rmean, col = magma(100), axes = FALSE, box = FALSE)
plot(log(rvar), col = magma(100), axes = FALSE, box = FALSE)

```

## Plotting Admixture Zones 

```{r, cache = TRUE, fig.width = 5, fig.height = 5}
rv_stack <- make_boundaries_allK(krig_list, boundaries = TRUE)
par(mfrow=c(1,1))
plot_boundaries(rv_stack)

par(mfrow=c(2,2), mar = rep (2,4))
plot_boundaries(rv_stack, option = "mean", log_transform = FALSE, main = "mean", tess3_obj = tess3_obj)
plot_boundaries(rv_stack, option = "mean", log_transform = TRUE, main = "log(mean)", tess3_obj = tess3_obj)
plot_boundaries(rv_stack, option = "weighted.mean", log_transform = FALSE, main = "weighted mean", tess3_obj = tess3_obj)
plot_boundaries(rv_stack, option = "weighted.mean", log_transform = TRUE, main = "log(weighted mean)", tess3_obj = tess3_obj)
```

```{r, cache = TRUE, fig.width = 5, fig.height = 5}
rv_stack <- make_boundaries_allK(krig_list, minQ = 0.9, boundaries = FALSE)
par(mfrow=c(1,1))
plot_boundaries(rv_stack)

par(mfrow=c(2,2), mar = rep(2,4))
plot_boundaries(rv_stack, option = "mean", log_transform = FALSE, main = "mean", tess3_obj = tess3_obj)
plot_boundaries(rv_stack, option = "mean", log_transform = TRUE, main = "log(mean)", tess3_obj = tess3_obj)
plot_boundaries(rv_stack, option = "weighted.mean", log_transform = FALSE, main = "weighted mean", tess3_obj = tess3_obj)
plot_boundaries(rv_stack, option = "weighted.mean", log_transform = TRUE, main = "log(weighted mean)", tess3_obj = tess3_obj)
```


