name: build

on:
  push:
    paths:
      - .github/workflows/build-test.yml
  pull_request:
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/thewanglab/algatr:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
  
      - name: Restore renv Environment
        run: R -e 'renv::restore()'
  
      - name: Build R Package
        run: R -e 'devtools::build()'
