name: build

on:
  push:
    paths:
      - "R/**.R"
      - .github/workflows/build-test.yml
      - "vignettes/**.Rmd"
      - "renv.lock"
    branches: [ "main" ]
  pull_request:
    paths:
        - "R/**.R"
        - .github/workflows/build-test.yml
        - "vignettes/**.Rmd"
        - "renv.lock"
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thewanglab/algatr:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build R Package
        run: R -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); update.packages(ask = FALSE); devtools::build()'

