name: build

on:
  push:
    paths:
      - .github/workflows/build-test.yml
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install renv
      run: R -e 'install.packages("renv")'

    - name: Restore renv Environment
      run: R -e 'renv::restore()'

    - name: Build R Package
      run: R -e 'devtools::build()'
