name: docker-build
on:
  push:
    paths:
      - "R/**.R"
      - "vignettes/**.Rmd"
      - .github/workflows/docker-image.yml
      - renv.lock
      - Dockerfile
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/thewanglab/algatr:latest
      - name: Publish
        run: docker push ghcr.io/thewanglab/algatr:latest
