name: quick-test

on:
  push:
    paths:
      - "R/**.R"
      - .github/workflows/quick-test.yml
      - "vignettes/**.Rmd"
      - "renv.lock"
    branches: [ "main" ]
  pull_request:
    paths:
        - "R/**.R"
        - .github/workflows/quick-test.yml
        - "vignettes/**.Rmd"
        - "renv.lock"
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thewanglab/algatr:latest
    steps:
      - uses: actions/checkout@v4

      - name: Set CRAN
        env:
          GITHUB_PAT: ${{ secrets.GITPAT }}
        run: |
          R -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'
         
      - name: Build R Package
        run: R -e 'devtools::build()'
